### ISSUE TITLE
[Discord] Invite link is expired 

### ISSUE THREAD

**Issue by mrchocha** [tramlinehq/tramline#717]
## Context
Not able to join discord channel as invite link is expired.

<img width="565" alt="image" src="https://github.com/user-attachments/assets/ae717278-d580-438c-ac97-3015e376f6b0" />

**Comment by nid90** [comment]
Thanks for pointing that out @mrchocha! I have fixed the link in our README. 🙇‍♀️

**Comment by Ayush-Dutt-Sharma** [comment]
@nid90 it is still broken
![Screenshot 2025-01-14 at 10 18 10 AM](https://github.com/user-attachments/assets/6726446c-f959-483c-87c7-8ae0d2785f71)

**Comment by nid90** [comment]
@Ayush-Dutt-Sharma can you tell me where you got that URL from? I have checked our [README](https://github.com/tramlinehq/tramline?tab=readme-ov-file#tramline), the link is not the same as the one in your screenshot.
